theme: jekyll-theme-hacker
title: TRQ20 Webpage
description: Este es un espacio para que puedan encontrar de forma ordenada todas las actividades y contenidos que vayamos desarrollando en las distintas materias que tengan conmigo.